M48
; DRILL file {KiCad (6.0.9)} date Wed Apr  5 21:44:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-05T21:44:48+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X2.2425Y-2.5606
X2.2425Y-2.7882
T2
X2.8504Y-4.6063
T0
M30
