M48
; DRILL file {KiCad 7.0.1} date Fri Apr 14 11:06:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-14T11:06:51+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X2.2425Y-2.5606
X2.2425Y-2.7882
T2
X2.8504Y-4.6063
T3
X4.6894Y-2.7154
T0
M30
